
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: 'root'   # Replace with your MySQL username
#   password: 'rootroot'   # Replace with your MySQL password
#   host: localhost                 # Use '127.0.0.1' or another host if different
#   port: 3306                      # Default MySQL port
#   socket: /tmp/mysql.sock         # Optional: depends on your MySQL installation

# development:
#   <<: *default
#   database: tripleseat_db # Replace with the database name from MySQL Workbench

# test:
#   <<: *default
#   database: tripleseat_db # Replace with the test database name

# production:
#   <<: *default
#   database: tripleseat_db # Replace with the production database name
#   username: <%= ENV['root'] %> # Use environment variables for security in production
#   password: <%= ENV['rootroot'] %>

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'root' 
  password: 'rootroot' 
  host: localhost  
  port: 3306  

development:
  <<: *default
  database: tripleseat_db 